### ISSUE TITLE
Renders tab as invalid char

### ISSUE THREAD

**Issue by samal-rasmussen** [chmln/betterWhiteSpace#1]
I'm on Windows 7 and Vs Code 1.11.1, and I get invalid chars rendered in place of tabs.

![better-whitespace-render-bug](https://cloud.githubusercontent.com/assets/1503031/25329501/4a730914-28dc-11e7-8014-4ea96f1636cd.png)

**Comment by dudeofawesome** [comment]
I'm also seeing this on macOS 10.11 with VS Code 1.11.2

**Comment by chmln** [comment]
Should be fixed in 1.0.1, please update and let me know if its fixed

**Comment by samal-rasmussen** [comment]
Well at least it indents the correct amount of pixels now, but it still shows an invalid character instead of a long line character for tabs (yes we use tabs in html):
![betterwhitespacebug](https://cloud.githubusercontent.com/assets/1503031/25736945/578990b8-3175-11e7-9052-703f969284be.png)

**Comment by sapegin** [comment]
Same issue on macOS:

![image 2017-05-13 at 10 59 21 am](https://cloud.githubusercontent.com/assets/70067/26024113/4e929516-37cb-11e7-8f55-26207a8f2266.png)

Also line height is changing so code is jumping around when you selecting it.

**Comment by chmln** [comment]
Hi all,

Thanks for the feedback.
After some research, I've found that only [limited number of fonts](http://www.fileformat.info/info/unicode/char/2e3b/fontsupport.htm) support the three-em-dash.

There's Segoe UI on Windows, but Linux/Mac factory-default fonts don't support the symbol.
Thus I've settled on the excellent Source Sans Pro.

I will list this on `README` too, but you need to have the Source Sans Pro font installed:
https://fonts.google.com/download?family=Source%20Sans%20Pro

I will publish a new version of the extension tomorrow.

**Comment by timpcc** [comment]
Has this new version been released? I've installed Source Sans Pro (on Windows 7) but I'm still getting the same issue as samal84. The version of BetterWhitespace on the marketplace is still 1.0.1.

**Comment by samal-rasmussen** [comment]
My "fix" for this issue was just to switch to WhiteViz.

https://marketplace.visualstudio.com/items?itemName=spywhere.whiteviz
https://github.com/spywhere/vscode-whiteviz
